# Generated by Django 2.0.1 on 2018-01-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pics/Screenshot_from_2018-01-17_21-53-31.png', upload_to='pics/'),
        ),
    ]
