# Generated by Django 2.0.1 on 2018-01-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180123_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(default='pics/profile-pictures.png', upload_to='cv/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pics/profile-pictures.png', upload_to='pics/'),
        ),
    ]
