# Generated by Django 2.0.1 on 2018-01-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180123_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdate',
            name='events',
        ),
        migrations.AddField(
            model_name='bookdate',
            name='events',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
            preserve_default=False,
        ),
    ]
