# Generated by Django 2.0.1 on 2018-01-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180123_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdate',
            old_name='events',
            new_name='event',
        ),
    ]
