# Generated by Django 2.0.1 on 2018-01-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180124_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdate',
            name='event',
            field=models.CharField(max_length=255),
        ),
    ]
