# Generated by Django 2.0.1 on 2018-01-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180125_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdate',
            name='interview',
            field=models.DateField(null=True),
        ),
    ]
