# Generated by Django 2.0.1 on 2018-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180125_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_start_date',
            field=models.DateField(null=True),
        ),
    ]
