# Generated by Django 2.0.1 on 2018-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180128_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_question',
            field=models.CharField(default='', max_length=200),
        ),
    ]
