# Generated by Django 2.0.1 on 2018-01-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_event_event_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdate',
            name='event_answer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bookdate',
            name='waitlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
