# Generated by Django 2.0.1 on 2018-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180128_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdate',
            name='timeslot',
            field=models.TimeField(null=True),
        ),
    ]
