# Generated by Django 2.0.1 on 2018-01-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_bookdate_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
    ]
