# Generated by Django 2.0.1 on 2018-02-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdate',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Timeslot'),
        ),
    ]
